name: "ğŸ›  Bug Report"
description: "Bugã«é–¢ã—ã¦ã®å ±å‘Šã§ã™ã€ç™ºç”Ÿã™ã‚‹ãƒšãƒ¼ã‚¸ã€æ“ä½œæµã‚Œã€ã‚¹ã‚¯ãƒªãƒ¼ãƒ³ã‚·ãƒ§ãƒƒãƒˆãªã©ã‚’è¨˜å…¥ã—ã¦ãã ã•ã„"
title: "[DevTools Bug]: ã“ã“ã«ã‚¿ã‚¤ãƒˆãƒ«ã‚’è¨˜å…¥ã—ã¦ãã ã•ã„"
labels: ["bug"]
body:
- type: input
  attributes:
    label: ãƒšãƒ¼ã‚¸ã®URL
    description: |
      BugãŒç™ºç”Ÿã™ã‚‹ãƒšãƒ¼ã‚¸ã®URLã§ã™
      ãƒ­ãƒ¼ã‚«ãƒ«URLã§ã‚‚è‰¯ã„ã§ã™ãŒè²¼ã£ã¦ãã ã•ã„
      ï¼ˆãƒ‡ãƒ—ãƒ­ã‚¤URLãŒã‚ã‚Œã°ã‚‚ã£ã¨ç†æƒ³ã§ã™ï¼‰
    placeholder: |
      http://localhost:3000/index.html
  validations:
    required: true
- type: textarea
  attributes:
    label: æ“ä½œã®æµã‚Œ
    description: |
      Bugã‚’å†ç¾ã•ã›ã‚‹ãŸã‚ã«ã€æ“ä½œã®æµã‚Œã‚’è©³ç´°ã«è¨˜å…¥ã—ã¦ãã ã•ã„
    placeholder: |
      1. ãƒ›ãƒ¼ãƒ ãƒšãƒ¼ã‚¸ã«è¡Œãã¾ã™
      2. å³ä¸Šã®ã‚¢ã‚¤ã‚³ãƒ³ã‚’ã‚¯ãƒªãƒƒã‚¯ã—ã¾ã™ã€æƒ…å ±å…¥åŠ›ãƒšãƒ¼ã‚¸ã«è¡Œãã¾ã™
      3. æƒ…å ±å…¥åŠ›ãƒšãƒ¼ã‚¸ã§ã€ã‚¢ã‚¤ãƒ†ãƒ åã‚’è¨˜å…¥ã—ã¾ã™
  validations:
    required: true
- type: dropdown
  attributes:
    label: ç™ºç”Ÿã®é »åº¦
    description: |
      Bugã®ç™ºç”Ÿé »åº¦ã‚’æ•™ãˆã¦ãã ã•ã„
    options:
      - æ¯å›ç™ºç”Ÿã—ã¾ã™
      - ã‚ˆãç™ºç”Ÿã—ã¾ã™
      - ãŸã‚ã«ç™ºç”Ÿã—ã¾ã™
      - ä¸€å›ã ã‘ç™ºç”Ÿã—ã¾ã™
  validations:
    required: true
- type: dropdown
  attributes:
    label: ãƒ‡ãƒã‚¤ã‚¹
    description: |
      ãƒ‡ãƒã‚¤ã‚¹ã®ç¨®é¡ã‚’ãŠæ•™ãˆãã ã•ã„
    options:
      - Mac
      - Windows
      - iPhone
      - Android
  validations:
    required: true
- type: input
  attributes:
    label: ãƒ‡ãƒã‚¤ã‚¹ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³
    description: |
      ãƒ‡ãƒã‚¤ã‚¹ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’ãŠæ•™ãˆãã ã•ã„
    placeholder: |
      iPhone 15.4
  validations:
    required: false
- type: dropdown
  attributes:
    label: ãƒ–ãƒ©ã‚¦ã‚¶ãƒ¼
    description: |
      ãƒ–ãƒ©ã‚¦ã‚¶ãƒ¼ã®ç¨®é¡ã‚’ãŠæ•™ãˆãã ã•ã„
    options:
      - Mac
      - Windows
      - iPhone
      - Android
  validations:
    required: true
- type: input
  attributes:
    label: ãƒ–ãƒ©ã‚¦ã‚¶ãƒ¼ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³
    description: |
      ãƒ–ãƒ©ã‚¦ã‚¶ãƒ¼ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’ãŠæ•™ãˆãã ã•ã„
    placeholder: |
      Chrome 99
  validations:
    required: false
- type: textarea
  attributes:
    label: å‚™è€ƒ
    description: |
      è£œè¶³äº‹é …ãŒã‚ã‚Œã°è¨˜å…¥ã—ã¦ãã ã•ã„
  validations:
    required: false